namespace AzureHookReceiver_Dojo.Model;

/// <summary>
/// Autogenerated classes by VS.
/// </summary>
public class WorkItemData
{
    public string? subscriptionId { get; set; }
    public int notificationId { get; set; }
    public string? id { get; set; }
    public string? eventType { get; set; }
    public string? publisherId { get; set; }
    public Resource? resource { get; set; }
}

public class Resource
{
    public int id { get; set; }
    public int workItemId { get; set; }
    public int rev { get; set; }
    public DateTime revisedDate { get; set; }
    public Fields? fields { get; set; }
    public Revision? revision { get; set; }
}

public class Fields
{
    public ChangeValue? SystemRev { get; set; }
    public ChangeValue? SystemAuthorizedDate { get; set; }
    public ChangeValue? SystemRevisedDate { get; set; }
    public ChangeValue? SystemState { get; set; }
    public ChangeValue? SystemReason { get; set; }
    public ChangeValue? SystemChangedDate { get; set; }
    public ChangeValue? SystemWatermark { get; set; }
    public ChangeValue? MicrosoftVSTSCommonStateChangeDate { get; set; }
    public NewValue? MicrosoftVSTSCommonClosedDate { get; set; }
    public NewValue? MicrosoftVSTSCommonClosedBy { get; set; }
}

public class ChangeValue
{
    public object? oldValue { get; set; }
    public object? newValue { get; set; }
}

public class NewValue
{
    public object? newValue { get; set; }
}

public class Revision
{
    public int id { get; set; }
    public int rev { get; set; }
    public Dictionary<string, object>? fields { get; set; }
}

